### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by abdullahaijaz** [GT4SD/zberta#9]
Hi, Thank you for your making this pipeline open source. I really appreciate that.

I am having an issue in BERTA instance while training. Please find the error and the code.

![image](https://user-images.githubusercontent.com/106417388/211003321-8da39791-d4e8-4ecb-af74-abd3bbcd9525.png)

![image](https://user-images.githubusercontent.com/106417388/211003426-e023fc25-2ed7-4293-9218-318b8eb45230.png)

Any solution/advice would be really appreciated. Thanks

**Comment by comidan** [comment]
Hello! Glad you like it! Ok thanks for reporting this, will look into this ASAP!

**Comment by comidan** [comment]
Hello @abdullahaijaz, I ran the interested cells you talked about using the environment where you experienced this (colab) and on the training task as you were doing.

The error you found is about the last layer of BERTA, the one making the NLI classification about a hypothesis being correlated or not (2 possible outputs) or being correlated, neutral or not correlated (3 possible outputs) hence the error you were facing in loading up something with a different classification layer in terms of shape.

The issue was related to a wrong linkage to the NLI model based on 3 possible outputs.
It has now been fixed, you can now try to reinstall the module and continue your training!

**Comment by abdullahaijaz** [comment]
Hi, @comidan many thanks for solving and explaining the issue as well.

I got one question though. Since you are using SNLI Corpus and Banking77-OOS Dataset in this pipeline. How can we train the BERT-A model with any other dataset other than Banking77-OOS to generate unknown intents? 

Thanks in advance.
